
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iodzeyxuoozuouljifmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZHpleXh1b296dW91bGppZm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODMyMzcsImV4cCI6MjA1ODU1OTIzN30.7O3HViGO5ZshXfJdzY2T1yqt9e0q15HFPcsgBoruysM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
